#!/bin/bash

blockMesh
rm -rf processor0 processor1 processor2 processor3
decomposePar
mpirun -np 4 snappyHexMesh -overwrite -parallel
reconstructParMesh -constant -mergeTol 1e-06
rm -rf processor0 processor1 processor2 processor3
foamToVTK
